
import React, { useState } from 'react';
import { Terminal, Copy, Check, Database, AlertCircle, Info, Zap } from 'lucide-react';

export const DatabaseSetup: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const sqlCode = `-- ==========================================
-- SCRIPT MESTRE: USINA DE BIOMETANO CAIEIRAS
-- MATRIZ GUT & GESTÃO DE ATIVOS (TAGS)
-- ==========================================

-- 1. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE ÁREAS (SUBSISTEMAS)
CREATE TABLE IF NOT EXISTS areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 3. TABELA DE EQUIPAMENTOS (ATIVOS)
CREATE TABLE IF NOT EXISTS equipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag TEXT,
  name TEXT UNIQUE NOT NULL,
  area_name TEXT REFERENCES areas(name) ON DELETE CASCADE,
  image_url TEXT,
  min_rotation FLOAT8 DEFAULT 0,
  max_rotation FLOAT8 DEFAULT 3600,
  min_temp FLOAT8 DEFAULT 20,
  max_temp FLOAT8 DEFAULT 85,
  last_maintenance DATE,
  last_lubrication DATE,
  technical_description TEXT,
  installation_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 4. TABELA DE OCORRÊNCIAS (MATRIZ GUT)
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  immediate_action TEXT,
  area TEXT NOT NULL,
  equipment_name TEXT,
  gravity INT4 DEFAULT 1,
  urgency INT4 DEFAULT 1,
  tendency INT4 DEFAULT 1,
  score INT4 DEFAULT 1,
  status TEXT DEFAULT 'Aberto',
  ai_suggestion TEXT,
  ai_action_suggestion TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE TERMOGRAFIA (MANUTENÇÃO PREDITIVA)
CREATE TABLE IF NOT EXISTS thermography (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT,
  area TEXT NOT NULL,
  current_temp FLOAT8 NOT NULL,
  max_temp FLOAT8 NOT NULL,
  min_temp FLOAT8 NOT NULL,
  last_inspection DATE,
  notes TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  ai_analysis TEXT,
  ai_recommendation TEXT,
  risk_level TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABELA DE CONFIGURAÇÕES (LIMITES DE RISCO)
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  critical_threshold INT4 DEFAULT 250,
  warning_threshold INT4 DEFAULT 100,
  individual_critical_threshold INT4 DEFAULT 80,
  individual_warning_threshold INT4 DEFAULT 40,
  accent_color TEXT DEFAULT '#10b981',
  color_normal TEXT DEFAULT '#10b981',
  color_warning TEXT DEFAULT '#f59e0b',
  color_critical TEXT DEFAULT '#ef4444'
);

-- ==========================================
-- SCRIPT DE SINCRONIZAÇÃO (CORREÇÃO DE ERROS)
-- RODE ESTE BLOCO SE RECEBER ERROS DE COLUNA
-- ==========================================

-- Correção Crítica para Equipamentos
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS installation_date DATE;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS tag TEXT;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS image_url TEXT;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS min_rotation FLOAT8;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS max_rotation FLOAT8;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS min_temp FLOAT8;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS max_temp FLOAT8;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS technical_description TEXT;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS last_maintenance DATE;
ALTER TABLE equipments ADD COLUMN IF NOT EXISTS last_lubrication DATE;

-- Atualização de Ocorrências GUT
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_suggestion TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS ai_action_suggestion TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS attachment_name TEXT;
ALTER TABLE issues ADD COLUMN IF NOT EXISTS equipment_name TEXT;

-- Atualização de Termografia
ALTER TABLE thermography ADD COLUMN IF NOT EXISTS ai_analysis TEXT;
ALTER TABLE thermography ADD COLUMN IF NOT EXISTS ai_recommendation TEXT;
ALTER TABLE thermography ADD COLUMN IF NOT EXISTS risk_level TEXT;
ALTER TABLE thermography ADD COLUMN IF NOT EXISTS attachment_url TEXT;
ALTER TABLE thermography ADD COLUMN IF NOT EXISTS attachment_name TEXT;

-- ==========================================
-- CONFIGURAÇÃO DE ARMAZENAMENTO (STORAGE)
-- ==========================================
-- 1. Vá em 'Storage' no menu lateral do Supabase.
-- 2. Crie um Bucket chamado: attachments
-- 3. Marque a opção 'Public' (Público).
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-20">
      <div className="bg-slate-900/60 border border-slate-800 rounded-[2.5rem] p-10 shadow-2xl overflow-hidden relative group">
        <div className="absolute -top-10 -right-10 text-blue-500/5 rotate-12">
           <Terminal size={240} />
        </div>
        
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-10 border-b border-slate-800 pb-8">
           <div className="flex items-center gap-4">
              <div className="p-4 bg-blue-600/10 text-blue-500 rounded-3xl border border-blue-500/20">
                 <Database size={32} />
              </div>
              <div>
                 <h2 className="text-2xl font-black text-white uppercase tracking-tight">Infraestrutura SQL Master</h2>
                 <p className="text-[10px] text-slate-500 font-black uppercase tracking-widest mt-1">Script de Configuração e Atualização Biometano</p>
              </div>
           </div>
           <button 
             onClick={handleCopy}
             className={`px-8 py-3.5 rounded-2xl font-black text-[10px] uppercase tracking-widest transition-all flex items-center gap-3 ${copied ? 'bg-green-600 text-white shadow-[0_0_20px_rgba(22,163,74,0.4)]' : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700 shadow-xl'}`}
           >
             {copied ? <Check size={16} /> : <Copy size={16} />}
             {copied ? 'Código Copiado!' : 'Copiar Script para Supabase'}
           </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
           <div className="lg:col-span-1 space-y-6">
              <div className="bg-red-950/20 p-6 rounded-3xl border border-red-900/40 space-y-3">
                 <h4 className="text-[10px] font-black text-red-500 uppercase tracking-widest flex items-center gap-2">
                    <AlertCircle size={14} /> Solução de Erros de Schema
                 </h4>
                 <p className="text-[11px] text-red-200/80 leading-relaxed font-medium">
                    Se você recebeu o erro <strong className="text-white">"Could not find the installation_date column"</strong>, copie este script e execute no SQL Editor do Supabase. Isso sincroniza as tabelas existentes com as novas funções do app.
                 </p>
                 <div className="pt-2">
                    <button onClick={handleCopy} className="text-[8px] font-black uppercase tracking-widest bg-red-500/20 text-red-400 px-3 py-1.5 rounded-lg border border-red-500/30">Copiar Script de Correção</button>
                 </div>
              </div>

              <div className="bg-slate-950/40 p-6 rounded-3xl border border-slate-800 space-y-4">
                 <h4 className="text-[10px] font-black text-white uppercase tracking-widest flex items-center gap-2">
                    <Info size={14} className="text-blue-500" /> Fluxo de Implantação
                 </h4>
                 <ol className="space-y-4">
                    {[
                      "Abra o 'SQL Editor' no seu painel Supabase.",
                      "Crie uma 'New Query' (Nova Consulta).",
                      "Cole o script copiado ao lado.",
                      "Clique em 'Run' (Executar).",
                      "Vá em 'Storage' e crie o bucket 'attachments' como público."
                    ].map((step, i) => (
                      <li key={i} className="flex gap-3 items-start">
                         <span className="w-5 h-5 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center text-[9px] font-black text-blue-500 shrink-0 mt-0.5">{i+1}</span>
                         <p className="text-[11px] text-slate-400 font-medium leading-relaxed">{step}</p>
                      </li>
                    ))}
                 </ol>
              </div>
           </div>

           <div className="lg:col-span-2">
              <div className="bg-slate-950 rounded-3xl border border-slate-800 shadow-inner overflow-hidden flex flex-col h-[600px] ring-1 ring-white/5">
                 <div className="bg-slate-900/50 px-6 py-3 border-b border-slate-800 flex justify-between items-center">
                    <div className="flex gap-1.5">
                       <div className="w-2 h-2 rounded-full bg-red-500/50"></div>
                       <div className="w-2 h-2 rounded-full bg-amber-500/50"></div>
                       <div className="w-2 h-2 rounded-full bg-green-500/50"></div>
                    </div>
                    <span className="text-[9px] font-black text-slate-600 uppercase tracking-widest">Full Schema Script v2.1</span>
                 </div>
                 <pre className="p-8 overflow-auto custom-scrollbar text-[11px] font-mono text-emerald-400/90 leading-relaxed selection:bg-emerald-500/20">
                    {sqlCode}
                 </pre>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};
