
import React, { useState } from 'react';
import { Terminal, Copy, Check, Database, AlertCircle, Info, Zap } from 'lucide-react';

export const DatabaseSetup: React.FC = () => {
  const [copied, setCopied] = useState(false);

  const sqlCode = `-- ==========================================
-- SCRIPT MESTRE ATUALIZADO: BIOMETANO CAIEIRAS
-- FOCO: FILTRAGEM SETORIAL E NOTIFICAÇÕES
-- ==========================================

-- 1. TABELA DE USUÁRIOS
CREATE TABLE IF NOT EXISTS users (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  password TEXT NOT NULL,
  role TEXT NOT NULL,
  sector TEXT, -- Setor do usuário (Mecânica, Elétrica, etc)
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 2. TABELA DE PERMISSÕES RBAC
CREATE TABLE IF NOT EXISTS role_permissions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  role TEXT UNIQUE NOT NULL,
  can_view_dashboard BOOLEAN DEFAULT TRUE,
  can_view_sector BOOLEAN DEFAULT TRUE,
  can_view_gut BOOLEAN DEFAULT TRUE,
  can_view_thermo BOOLEAN DEFAULT TRUE,
  can_view_vibration BOOLEAN DEFAULT TRUE,
  can_view_assets BOOLEAN DEFAULT TRUE,
  can_view_users BOOLEAN DEFAULT FALSE,
  can_view_settings BOOLEAN DEFAULT FALSE,
  can_view_reports BOOLEAN DEFAULT FALSE
);

-- 3. TABELA DE ÁREAS (SUBSISTEMAS)
CREATE TABLE IF NOT EXISTS areas (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- 4. TABELA DE EQUIPAMENTOS (ATIVOS)
CREATE TABLE IF NOT EXISTS equipments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  tag TEXT,
  name TEXT UNIQUE NOT NULL,
  area_name TEXT REFERENCES areas(name) ON DELETE CASCADE,
  image_url TEXT,
  min_rotation FLOAT8 DEFAULT 0,
  max_rotation FLOAT8 DEFAULT 3600,
  min_temp FLOAT8 DEFAULT 20,
  max_temp FLOAT8 DEFAULT 85,
  last_maintenance DATE,
  last_lubrication DATE,
  technical_description TEXT,
  installation_date DATE,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 5. TABELA DE OCORRÊNCIAS (MATRIZ GUT)
CREATE TABLE IF NOT EXISTS issues (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  immediate_action TEXT,
  area TEXT NOT NULL,
  sector TEXT, -- NOVO: Atribuição de setor (Mecânica e lub, Elétrica e instr, etc)
  equipment_name TEXT,
  gravity INT4 DEFAULT 1,
  urgency INT4 DEFAULT 1,
  tendency INT4 DEFAULT 1,
  score INT4 DEFAULT 1,
  status TEXT DEFAULT 'Aberto',
  ai_suggestion TEXT,
  ai_action_suggestion TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  resolution TEXT,
  ai_resolution_evaluation TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 6. TABELA DE TERMOGRAFIA
CREATE TABLE IF NOT EXISTS thermography (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT,
  area TEXT NOT NULL,
  current_temp FLOAT8 NOT NULL,
  max_temp FLOAT8 NOT NULL,
  min_temp FLOAT8 NOT NULL,
  last_inspection DATE,
  notes TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  ai_analysis TEXT,
  ai_recommendation TEXT,
  risk_level TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 7. TABELA DE VIBRAÇÃO
CREATE TABLE IF NOT EXISTS vibration (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  equipment_name TEXT,
  area TEXT NOT NULL,
  overall_velocity FLOAT8 NOT NULL,
  acceleration FLOAT8 NOT NULL,
  peak_frequency FLOAT8,
  last_inspection DATE,
  notes TEXT,
  attachment_url TEXT,
  attachment_name TEXT,
  ai_analysis TEXT,
  ai_recommendation TEXT,
  risk_level TEXT,
  created_at TIMESTAMPTZ DEFAULT NOW()
);

-- 8. TABELA DE CONFIGURAÇÕES
CREATE TABLE IF NOT EXISTS settings (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  critical_threshold INT4 DEFAULT 250,
  warning_threshold INT4 DEFAULT 100,
  individual_critical_threshold INT4 DEFAULT 80,
  individual_warning_threshold INT4 DEFAULT 40,
  accent_color TEXT DEFAULT '#10b981',
  color_normal TEXT DEFAULT '#10b981',
  color_warning TEXT DEFAULT '#f59e0b',
  color_critical TEXT DEFAULT '#ef4444'
);

-- ==========================================
-- SCRIPT DE MIGRAÇÃO (PARA BASES JÁ CRIADAS)
-- ==========================================

-- Adicionar campo SECTOR na tabela de ISSUES se não existir
ALTER TABLE issues ADD COLUMN IF NOT EXISTS sector TEXT;

-- Adicionar campo SECTOR na tabela de USERS se não existir
ALTER TABLE users ADD COLUMN IF NOT EXISTS sector TEXT;

-- Garantir colunas de permissão
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS can_view_vibration BOOLEAN DEFAULT TRUE;
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS can_view_reports BOOLEAN DEFAULT FALSE;
ALTER TABLE role_permissions ADD COLUMN IF NOT EXISTS can_view_sector BOOLEAN DEFAULT TRUE;

-- Criar tabela de SECTORES se desejar controle rigoroso (opcional)
CREATE TABLE IF NOT EXISTS sectors (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT UNIQUE NOT NULL
);

-- Inserir setores padrão se a tabela estiver vazia
INSERT INTO sectors (name) 
VALUES ('Mecanica e lub'), ('eletrica e instrumentação'), ('operação'), ('quimica')
ON CONFLICT (name) DO NOTHING;

-- Atualizar permissões para Desenvolvedor e Administrador
UPDATE role_permissions 
SET can_view_vibration = true, can_view_reports = true, can_view_sector = true
WHERE role IN ('Desenvolvedor', 'Administrador');
`;

  const handleCopy = () => {
    navigator.clipboard.writeText(sqlCode);
    setCopied(true);
    setTimeout(() => setCopied(false), 2000);
  };

  return (
    <div className="space-y-8 animate-fade-in pb-20">
      <div className="bg-slate-900/60 border border-slate-800 rounded-[2.5rem] p-10 shadow-2xl overflow-hidden relative group">
        <div className="absolute -top-10 -right-10 text-blue-500/5 rotate-12">
           <Terminal size={240} />
        </div>
        
        <div className="relative z-10 flex flex-col md:flex-row justify-between items-start md:items-center gap-6 mb-10 border-b border-slate-800 pb-8">
           <div className="flex items-center gap-4">
              <div className="p-4 bg-blue-600/10 text-blue-500 rounded-3xl border border-blue-500/20">
                 <Database size={32} />
              </div>
              <div>
                 <h2 className="text-2xl font-black text-white uppercase tracking-tight">Infraestrutura SQL Master v2.5</h2>
                 <p className="text-[10px] text-slate-500 font-black uppercase tracking-widest mt-1">Suporte para Notificações, Setores e Preditiva</p>
              </div>
           </div>
           <button 
             onClick={handleCopy}
             className={`px-8 py-3.5 rounded-2xl font-black text-[10px] uppercase tracking-widest transition-all flex items-center gap-3 ${copied ? 'bg-green-600 text-white shadow-[0_0_20px_rgba(22,163,74,0.4)]' : 'bg-slate-800 text-slate-300 hover:bg-slate-700 border border-slate-700 shadow-xl'}`}
           >
             {copied ? <Check size={16} /> : <Copy size={16} />}
             {copied ? 'Código Copiado!' : 'Copiar Script para Supabase'}
           </button>
        </div>

        <div className="grid grid-cols-1 lg:grid-cols-3 gap-8">
           <div className="lg:col-span-1 space-y-6">
              <div className="bg-red-950/20 p-6 rounded-3xl border border-red-900/40 space-y-3">
                 <h4 className="text-[10px] font-black text-red-500 uppercase tracking-widest flex items-center gap-2">
                    <AlertCircle size={14} /> Atualização Crítica
                 </h4>
                 <p className="text-[11px] text-red-200/80 leading-relaxed font-medium">
                    Para que o <strong className="text-white">Sininho de Notificações</strong> funcione, a coluna <code className="text-white bg-black/30 px-1 rounded">sector</code> deve existir na tabela <code className="text-white bg-black/30 px-1 rounded">issues</code>. Execute este script para garantir que todos os campos novos estejam presentes.
                 </p>
              </div>

              <div className="bg-slate-950/40 p-6 rounded-3xl border border-slate-800 space-y-4">
                 <h4 className="text-[10px] font-black text-white uppercase tracking-widest flex items-center gap-2">
                    <Info size={14} className="text-blue-500" /> Como Aplicar
                 </h4>
                 <ol className="space-y-4">
                    {[
                      "Abra o painel do Supabase.",
                      "Vá em 'SQL Editor' na barra lateral esquerda.",
                      "Clique em '+ New Query'.",
                      "Cole o código copiado deste painel.",
                      "Clique em 'Run' (ou Command/Ctrl + Enter).",
                      "Verifique se as tabelas agora possuem o campo 'sector'."
                    ].map((step, i) => (
                      <li key={i} className="flex gap-3 items-start">
                         <span className="w-5 h-5 rounded-full bg-slate-900 border border-slate-800 flex items-center justify-center text-[9px] font-black text-blue-500 shrink-0 mt-0.5">{i+1}</span>
                         <p className="text-[11px] text-slate-400 font-medium leading-relaxed">{step}</p>
                      </li>
                    ))}
                 </ol>
              </div>
           </div>

           <div className="lg:col-span-2">
              <div className="bg-slate-950 rounded-3xl border border-slate-800 shadow-inner overflow-hidden flex flex-col h-[600px] ring-1 ring-white/5">
                 <div className="bg-slate-900/50 px-6 py-3 border-b border-slate-800 flex justify-between items-center">
                    <div className="flex gap-1.5">
                       <div className="w-2 h-2 rounded-full bg-red-500/50"></div>
                       <div className="w-2 h-2 rounded-full bg-amber-500/50"></div>
                       <div className="w-2 h-2 rounded-full bg-green-500/50"></div>
                    </div>
                    <span className="text-[9px] font-black text-slate-600 uppercase tracking-widest">SQL Script v2.5.0</span>
                 </div>
                 <pre className="p-8 overflow-auto custom-scrollbar text-[11px] font-mono text-emerald-400/90 leading-relaxed selection:bg-emerald-500/20">
                    {sqlCode}
                 </pre>
              </div>
           </div>
        </div>
      </div>
    </div>
  );
};
